version: "3.8"

services:
  backend:
    image: frantomasino/my-app:latest
    container_name: backend_app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://franciscotomasino2:quilmes@cluster0.tpv8y.mongodb.net/ecomer?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=supersecretkey
      - PORT=8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
